"use client";
import {useState} from "react";
import {LayoutDashboard,Building2,Briefcase,Users,CalendarDays,ClipboardCheck,FileText,Settings,HelpCircle,Bell,Search,Plus,CheckCircle2,Menu,X,MapPin,Clock3,ShieldCheck,ChevronDown,LogOut} from "lucide-react";

type Section="Overview"|"Company Profile"|"Jobs"|"Applications"|"Interviews"|"Evaluations"|"Offers";
const nav:[Section,any][]=[["Overview",LayoutDashboard],["Company Profile",Building2],["Jobs",Briefcase],["Applications",Users],["Interviews",CalendarDays],["Evaluations",ClipboardCheck],["Offers",FileText]];
const apps=["Ananya Sharma","Rahul Kumar","Megha R","Arjun S"], roles=["Frontend Developer Intern","Backend Developer Intern","Data Analyst Intern","Full Stack Intern"];
export default function Page(){const [active,setActive]=useState<Section>("Overview"),[mobile,setMobile]=useState(false),[toast,setToast]=useState("");const notify=(x:string)=>{setToast(x);setTimeout(()=>setToast(""),2200)};return <div className="shell">
<aside className={mobile?"side open":"side"}><div className="brand"><div className="logo">VIC</div><div><b>Visionary Interns Club</b><small>Company Portal</small></div><button className="close" onClick={()=>setMobile(false)}><X size={18}/></button></div><div className="workspace"><small>WORKSPACE</small><div className="company"><div className="companyIcon">T</div><div><b>Tenar</b><span>Verified company</span></div><ChevronDown size={14}/></div></div><nav>{nav.map(([name,Icon])=><button key={name} className={active===name?"nav active":"nav"} onClick={()=>{setActive(name);setMobile(false)}}><Icon size={17}/>{name}</button>)}</nav><div className="sideBottom"><button className="nav" onClick={()=>notify("Help center opened") }><HelpCircle size={17}/>Help & Support</button><button className="nav" onClick={()=>notify("Settings opened") }><Settings size={17}/>Settings</button><div className="user"><div className="avatar">TS</div><div><b>Company Admin</b><span>admin@tenar.com</span></div><LogOut size={14}/></div></div></aside>
{mobile&&<button className="backdrop" onClick={()=>setMobile(false)}/>}
<main><header><button className="hamb" onClick={()=>setMobile(true)}><Menu/></button><div className="crumb">Company / <b>{active}</b></div><div className="actions"><div className="search"><Search size={15}/><input placeholder="Search candidates..."/></div><button className="icon"><Bell size={17}/><i/></button><div className="topUser"><div className="avatar">TS</div><div><b>Tenar</b><span>Company Admin</span></div></div></div></header>
<div className="content">{active==="Overview"&&<Overview go={setActive} notify={notify}/>} {active==="Company Profile"&&<Profile notify={notify}/>} {active==="Jobs"&&<Jobs notify={notify}/>} {active==="Applications"&&<Applications notify={notify}/>} {active==="Interviews"&&<Interviews notify={notify}/>} {active==="Evaluations"&&<Evaluations notify={notify}/>} {active==="Offers"&&<Offers notify={notify}/>}</div></main>{toast&&<div className="toast"><CheckCircle2 size={16}/>{toast}</div>}</div>}
function Title({title,sub,action}:{title:string,sub:string,action?:React.ReactNode}){return <div className="title"><div><span className="eyebrow">COMPANY WORKSPACE</span><h1>{title}</h1><p>{sub}</p></div>{action}</div>}
function Stat({icon:Icon,label,value,note}:{icon:any,label:string,value:string,note:string}){return <div className="stat"><div className="statIcon"><Icon size={18}/></div><div><span>{label}</span><b>{value}</b><small>{note}</small></div></div>}
function Overview({go,notify}:{go:(x:Section)=>void,notify:(x:string)=>void}){return <><Title title="Good evening, Tenar." sub="Manage your internship hiring pipeline from one place." action={<button className="primary" onClick={()=>go("Jobs")}><Plus size={15}/>Create job</button>}/><div className="stats"><Stat icon={Briefcase} label="Active jobs" value="2" note="+1 this month"/><Stat icon={Users} label="Applications" value="83" note="+18 this week"/><Stat icon={CalendarDays} label="Interviews" value="12" note="4 today"/><Stat icon={FileText} label="Offers sent" value="7" note="2 awaiting response"/></div><div className="twocol"><section className="card"><Head title="Hiring pipeline" sub="Current candidates across open roles." action="View all" onClick={()=>go("Applications")}/>{[["Applied",31],["Shortlisted",22],["Interview",12],["Offer",7],["Hired",4]].map(x=><div className="pipe" key={x[0] as string}><div><span>{x[0]}</span><b>{x[1]}</b></div><div className="bar"><i style={{width:`${Number(x[1])/83*100}%`}}/></div></div>)}</section><section className="card"><Head title="Today" sub="Next hiring activities."/><Activity t="10:30 AM" n="Ananya Sharma" s="Frontend interview"/><Activity t="01:00 PM" n="Rahul Kumar" s="Backend interview"/><Activity t="03:30 PM" n="Megha R" s="Evaluation due"/><button className="secondary full" onClick={()=>go("Interviews")}>Open calendar</button></section></div><section className="card"><Head title="Recent applications" sub="Latest candidates entering your pipeline." action="See applications" onClick={()=>go("Applications")}/><Table notify={notify}/></section><section className="card onboarding"><div className="onIcon"><ShieldCheck size={21}/></div><div><h3>Complete your company profile</h3><p>Add your description, website, logo and hiring preferences.</p></div><button className="secondary" onClick={()=>go("Company Profile")}>Complete profile</button></section></>}
function Head({title,sub,action,onClick}:{title:string,sub:string,action?:string,onClick?:()=>void}){return <div className="head"><div><h2>{title}</h2><p>{sub}</p></div>{action&&<button className="link" onClick={onClick}>{action}</button>}</div>}
function Activity({t,n,s}:{t:string,n:string,s:string}){return <div className="activity"><time>{t}</time><div><b>{n}</b><span>{s}</span></div></div>}
function Table({notify}:{notify:(x:string)=>void}){return <div className="table"><table><thead><tr><th>Candidate</th><th>Position</th><th>Stage</th><th>Score</th><th>Date</th><th/></tr></thead><tbody>{apps.map((n,i)=><tr key={n}><td><div className="candidate"><div className="avatar">{n.split(" ").map(x=>x[0]).join("")}</div><b>{n}</b></div></td><td>{roles[i]}</td><td><span className="badge">{["Interview","Shortlisted","Applied","Offer"][i]}</span></td><td><b>{[86,82,74,91][i]}%</b></td><td>Aug {11-i}, 2026</td><td><button className="link" onClick={()=>notify(`Opening ${n}'s application`)}>View</button></td></tr>)}</tbody></table></div>}
function Profile({notify}:{notify:(x:string)=>void}){return <><Title title="Company profile" sub="Keep your public company information accurate and student-friendly." action={<button className="primary" onClick={()=>notify("Company profile saved")}>Save changes</button>}/><div className="profile"><section className="card"><div className="profileTop"><div className="bigLogo">T</div><button className="secondary" onClick={()=>notify("Logo upload ready to connect")}>Change logo</button></div><div className="form"><label>Company name<input defaultValue="Tenar"/></label><label>Website<input defaultValue="https://tenar.com"/></label><label>Industry<input defaultValue="Technology"/></label><label>Company size<input defaultValue="51–200 employees"/></label><label>Location<input defaultValue="Bengaluru, Karnataka"/></label><label>Contact email<input defaultValue="careers@tenar.com"/></label><label className="wide">Company description<textarea defaultValue="Tenar builds technology solutions and creates practical internship opportunities for emerging talent."/></label></div></section><section className="card completion"><div className="ring"><b>82%</b><span>Complete</span></div><h2>Profile strength</h2><p>A complete profile helps students understand your company before applying.</p>{["Company description","Website","Industry","Company size","Hiring preferences"].map((x,i)=><div className="check" key={x}><CheckCircle2 size={14}/><span>{x}</span><small>{i<4?"Done":"Add"}</small></div>)}</section></div></>}
function Jobs({notify}:{notify:(x:string)=>void}){let data=[["Frontend Developer Intern","Bengaluru · Hybrid",38,"Active"],["Backend Developer Intern","Remote · India",26,"Active"],["Data Analyst Intern","Bengaluru · On-site",19,"Draft"]];return <><Title title="Jobs" sub="Create and manage internship opportunities." action={<button className="primary" onClick={()=>notify("Job creation form opened")}><Plus size={15}/>Create job</button>}/><div className="jobGrid">{data.map(j=><section className="card job" key={j[0] as string}><span className={j[3]==="Active"?"badge green":"badge"}>{j[3]}</span><h2>{j[0]}</h2><p><MapPin size={13}/>{j[1]}</p><div className="jobMeta"><span><Users size={13}/>{j[2]} applicants</span><span>Posted Aug 07</span></div><div className="jobActions"><button className="secondary" onClick={()=>notify(`Opening ${j[0]}`)}>View</button><button className="primary" onClick={()=>notify("Edit job opened")}>Edit</button></div></section>)}</div></>}
function Applications({notify}:{notify:(x:string)=>void}){return <><Title title="Applications" sub="Review and move students through your hiring pipeline." action={<button className="secondary" onClick={()=>notify("Filters opened")}>Filter applications</button>}/><section className="card"><Table notify={notify}/></section></>}
function Interviews({notify}:{notify:(x:string)=>void}){return <><Title title="Interviews" sub="Schedule and track candidate interviews." action={<button className="primary" onClick={()=>notify("Interview scheduler opened")}><Plus size={15}/>Schedule interview</button>}/><section className="card"><div className="dateHead"><b>August 11, 2026</b><span>Today</span></div>{[["10:30 AM","Ananya Sharma","Frontend Developer Intern"],["01:00 PM","Rahul Kumar","Backend Developer Intern"],["03:30 PM","Megha R","Data Analyst Intern"]].map(x=><div className="interview" key={x[1]}><time><Clock3 size={14}/>{x[0]}</time><div className="avatar">{x[1].split(" ").map(y=>y[0]).join("")}</div><div className="info"><b>{x[1]}</b><span>{x[2]}</span><small>Technical / manager round</small></div><button className="secondary" onClick={()=>notify(`Opening meeting for ${x[1]}`)}>Open</button></div>)}</section></>}
function Evaluations({notify}:{notify:(x:string)=>void}){return <><Title title="Evaluations" sub="Review interviewer feedback and hiring decisions."/><section className="card list">{[["Ananya Sharma","Frontend Developer Intern","Pending"],["Rahul Kumar","Backend Developer Intern","Completed"],["Megha R","Data Analyst Intern","Pending"]].map(x=><div className="listRow" key={x[0]}><div className="avatar">{x[0].split(" ").map(y=>y[0]).join("")}</div><div><b>{x[0]}</b><span>{x[1]} · Technical evaluation</span></div><em className={x[2]==="Completed"?"badge green":"badge"}>{x[2]}</em><button className="secondary" onClick={()=>notify(`Evaluation for ${x[0]} opened`)}>{x[2]==="Completed"?"Review":"Evaluate"}</button></div>)}</section></>}
function Offers({notify}:{notify:(x:string)=>void}){return <><Title title="Offers" sub="Generate and track internship offers." action={<button className="primary" onClick={()=>notify("Offer generator opened")}><Plus size={15}/>Generate offer</button>}/><section className="card list">{[["Arjun S","Full Stack Intern","₹25,000 / month","Sent"],["Priya N","Frontend Intern","₹22,000 / month","Accepted"],["Kiran M","Backend Intern","₹25,000 / month","Draft"]].map(x=><div className="listRow" key={x[0]}><div className="offerIcon"><FileText size={17}/></div><div><b>{x[0]}</b><span>{x[1]}</span></div><strong>{x[2]}</strong><em className={x[3]==="Accepted"?"badge green":"badge"}>{x[3]}</em><button className="secondary" onClick={()=>notify(`Opening offer for ${x[0]}`)}>View</button></div>)}</section></>}
